### ISSUE TITLE
Ambiguous occurrence ‘die’ (GHC 7.10)

### ISSUE THREAD

**Issue by Fuuzetsu** [gtk2hs/gtk2hs#100]
SetupWrapper.hs:91:17:
    Ambiguous occurrence ‘die’
    It could refer to either ‘Distribution.Simple.Utils.die’,
                             imported from ‘Distribution.Simple.Utils’ at SetupWrapper.hs:8:1-32
                          or ‘System.Exit.die’,
                             imported from ‘System.Exit’ at SetupWrapper.hs:21:1-18

**Comment by GeorgeCo** [comment]
basically, the same problem was in glib, reported in #87, I would think the fix is the same

**Comment by peti** [comment]
It appears that the fix is in Git already (https://github.com/gtk2hs/gtk2hs/commit/e150f4448d6fb7da1c66561fd7aa3b207eff598c). It's just that no update has been released to Hackage for the last 3 months.

**Comment by edsko** [comment]
Bump. This issue is the only problem stopping the gtk bindings from building on GHC 7.10.

**Comment by GeorgeCo** [comment]
seems to be fixed now, I can install gtk on ghc 7.10.1

**Comment by hamishmack** [comment]
Was waiting to fix #88 before updating hackage (since it also prevented installing on 7.10.1).  Both should be fixed in hackage now.
