### ISSUE TITLE
Cannot find glib-2.0

### ISSUE THREAD

**Issue by Snoxicle** [gtk2hs/gtk2hs#102]
(Fedora, 'cabal install gtk' and cabal install of git clone, gtk build tools installed fine) setup: The pkg-config package 'glib-2.0' is required but it could not be
found.
Failed to install glib-0.13.1.0

**Comment by hamishmack** [comment]
Most like means you do not have the `-devel` package installed for glib (C header files and libraries needed to build a Gtk application).   To install it run:

    sudo yum install glib2-devel

There are other similar packages for other Gtk libraries used by Gtk2Hs.  You can get most of them with:

     sudo yum install webkitgtk3-devel gtksourceview3-devel
