### ISSUE TITLE
Missing Widgets

### ISSUE THREAD

**Issue by jplatte** [gtk2hs/gtk2hs#106]
Hi, I just started using gtk2hs and I really like it, however there are quite some Widgets missing from Gtk+ 3 (GtkStack, GtkHeaderBar and GtkListBox are the ones I've encountered so far).

Is there any documentation on how to wrap new Widgets, or maybe an IRC channel? I'd happily create the new Widget wrappers myself, but I would need some help getting started with that.

**Comment by hamishmack** [comment]
I have been adding and updating things manually.  I copy the Gtk docs for the functions I want to add then convert them manually.  I believe there were perl scripts to automate this, but I am not sure how to use them.  In the long run it would be nice to use [haskell-gi](https://github.com/garetxe/haskell-gi) for generating the code, but I am not sure what would be involved.

There is an IRC channel #gtk2hs.

**Comment by jplatte** [comment]
Okay, thanks for the info. I'll go onto the IRC channel and see if I can contribute to the GObject introspection stuff, I think that would be better than adding things manually.
