### ISSUE TITLE
"Wordzu" and "Intzu" type naming failure while building on Windows

### ISSUE THREAD

**Issue by tejon** [gtk2hs/gtk2hs#110]
This occurs separately in both `pango` and `gtk3`. Each produces numerous errors like:

    GraphicsRenderingPangoStructs.hsc:79:21:
        Not in scope: type constructor or class `Wordzu'

(also Intzu). In the .hsc these are the template `#gtk2hs_type`, defined in `template-hsc-gtk2hs.h`. [On a hunch gleaned from Stack Exchange](http://stackoverflow.com/questions/15610053/correct-printf-format-specifier-for-size-t-zu-or-iu), I was able to build successfully by changing line 8 from

    printf ("%s%" G_GSIZE_FORMAT,

to

    printf ("%s%Iu",

but this doesn't explain why it failed in the first place, since `G_GSIZE_FORMAT` expands to "zu" and %zu is supposedly correct -- but explicit `"%s%zu"` also failed. (I rigorously ruled out path contamination and got the same results with both gcc 4.6.3 and 4.9.2.)

This seems very likely to be an upstream error, but I don't know where and there _is_ a functioning workaround here, so I figured I'd submit it.

**Comment by conklech** [comment]
Reporting the same error. Windows, MSYS2, GHC 7.8.4 and GHC 7.10.1 both give the same error. I'm building with `stack`. I haven't yet tried the suggested fix.

I also got a possibly-unrelated set of errors/warnings at the top of the `pango` build:

    Preprocessing library pango-0.13.1.0...
    realgcc.exe: unrecognized option '-pthread'
    realgcc.exe: unrecognized option '-pthread'

**Comment by conklech** [comment]
Suspecting Alexpux/MSYS2-packages#79 as the upstream bug. As reported there, MSYS2 uses newlib as its C library, which apparently doesn't support C99 printf formats.

Changing the format string to `"%s%u"` also resolves it. 

See the workaround [here](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libxml2/0020-fix-size_t-format-specifier.all.patch) in a different MSYS2 package.

**Comment by conklech** [comment]
Note that this is kind of a compound bug. On the one hand, the GCC shipped with GHC (which comes from one of the mingw projects) doesn't support `%zu`, which it should. On the other hand, the glib-2.0 headers in the MSYS2/mingw64 package don't define `G_GSIZE_FORMAT` correctly. (Who knows why; that's supposed to be an auto-generated file.)

I've reported the latter bug upstream. I'm not familiar with that project, and don't know if/when we could expect it to be resolved.

In the mean while, we can work around the problem by modifying the macro as follows. (I don't know jack about C; please rewrite idiomatically.)

    #if defined(__MINGW32_MAJOR_VERSION)
    #define _TEMPLATE_HSC_GTK2HS_H_GSIZE_FORMAT "u"
    #else
    #define _TEMPLATE_HSC_GTK2HS_H_GSIZE_FORMAT G_GSIZE_FORMAT
    #endif


    #define hsc_gtk2hs_type(t)                        \
      if ((t)(int)(t)1.4 == (t)1.4)                   \
        printf ("%s%" _TEMPLATE_HSC_GTK2HS_H_GSIZE_FORMAT, \
    // rest of file unchanged

**Comment by conklech** [comment]
A MSYS2 project member indicated that the proper resolution is to pass `-D__USE_MINGW_ANSI_STDIO=1` to the compiler to enable ANSI compatible stdio. That resolves it here. Pull request incoming.

**Comment by mwu-tow** [comment]
Could you upload fixed version of `cairo` onto Hackage? The issue was closed few months ago but the fix is not visible to most of the users.
