### ISSUE TITLE
Ambiguous reference

### ISSUE THREAD

**Issue by djvs** [gtk2hs/gtk2hs#129]
ϡ cabal install glib
    Resolving dependencies...
    Configuring glib-0.13.2.1...
    Failed to install glib-0.13.2.1
    Build log ( /home/d/.cabal/logs/glib-0.13.2.1.log ):
    cabal: Error: some packages failed to install:
    glib-0.13.2.1 failed during the configure step. The exception was:
    user error ('/usr/bin/ghc' exited with an error:

    /tmp/cabal-tmp-32674/glib-0.13.2.1/SetupWrapper.hs:60:49:
    Ambiguous occurrence `exeExtension'
    It could refer to either `Distribution.Simple.BuildPaths.exeExtension',
    imported from `Distribution.Simple.BuildPaths' at
    /tmp/cabal-tmp-32674/glib-0.13.2.1/SetupWrapper.hs:11:40-51
    or `System.Directory.exeExtension',
    imported from `System.Directory' at
    /tmp/cabal-tmp-32674/glib-0.13.2.1/SetupWrapper.hs:23:1-23
    (and originally defined in
    `directory-1.2.4.0:System.Directory.Internal.Config')
    )

build environment:

    ϡ cabal --version
    cabal-install version 1.22.6.0
    using version 1.22.4.0 of the Cabal library 
    ϡ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.6.3

**Comment by djvs** [comment]
Same problem with cairo

**Comment by hamishmack** [comment]
Because it has a custom Setup.hs file the Cabal library that will actually be used is the one in the `ghc-pkg list` output.  If that one looks out of date, you should be able to install a newer one by running `cabal install Cabal`.

**Comment by hasufell** [comment]
That doesn't work. I also have the latest cabal installed and it shows up in `ghc-pkg list`. This makes it effectively impossible to do gtk related GUI programming atm.

**Comment by hasufell** [comment]
This isn't related to the cabal version, but simply a build system bug caused by the imports:
here you import `exeExtension` https://github.com/gtk2hs/gtk2hs/blob/master/glib/SetupWrapper.hs#L11

and here it gets imported too, because it's neither hidden, nor a qualified import: https://github.com/gtk2hs/gtk2hs/blob/master/glib/SetupWrapper.hs#L23

the `exeExtension` function was added to the `directory` package in verison `1.2.4.0`
