### ISSUE TITLE
Seg fault calling widgetShowAll

### ISSUE THREAD

**Issue by ankhers** [gtk2hs/gtk2hs#137]
I have a little dummy project [here](https://github.com/ankhers/dashboards/tree/network) that is causing a seg fault when calling `widgetShowAll`.

Unfortunately, I am new to both Haskell and GTK and am not entirely sure how to go about debugging this. Just let me know what I can do to help find the problem.

Steps to reproduce:

1. Start the server application
2. Start 2 instances of the client application
3. Click anywhere within the window of either application, a button should be created in both instances of the application. (It isn't as common, but I have had the application seg fault here before)
4. Again, click anywhere within the window of either application, a button should be created in the instance that was clicked, and the instance that was not clicked should seg fault.

The application appears to crash on [this](https://github.com/ankhers/dashboards/blob/network/dashboards-client/app/Main.hs#L65) line.

I'm on OSX 10.10.5.
I'm using `stack` to build the applications.

Please let me know if there is anything else needed in order to debug this issue.

**Comment by hamishmack** [comment]
You need to make all Gtk calls on the thread that calls mainGUI.  Luckily there is an easy way to do this using `postGUISync` and `postGUIAsync`.

Try changing this line from

``` Haskell
      Right s -> createButton' fixed s
````

to

``` Haskell
      Right s -> postGUIAsync $ createButton' fixed s
````

**Comment by ankhers** [comment]
That seemed to do it. Thanks for the tip!
