### ISSUE TITLE
cabal install glib fails on ghc 8

### ISSUE THREAD

**Issue by GeorgeCo** [gtk2hs/gtk2hs#154]
cabal install glib
cabal install glib
Resolving dependencies...
Configuring glib-0.13.2.2...
Failed to install glib-0.13.2.2
Build log ( /Users/gcolpitts/.cabal/logs/glib-0.13.2.2.log ):
cabal: Entering directory '/var/folders/9b/rh4y2gy92hgdb6ktv4df1jv00000gn/T/cabal-tmp-74552/glib-0.13.2.2'
cabal: Leaving directory '/var/folders/9b/rh4y2gy92hgdb6ktv4df1jv00000gn/T/cabal-tmp-74552/glib-0.13.2.2'
cabal: Error: some packages failed to install:
glib-0.13.2.2 failed during the configure step. The exception was:
user error ('/usr/local/bin/ghc' exited with an error:

/var/folders/9b/rh4y2gy92hgdb6ktv4df1jv00000gn/T/cabal-tmp-74552/glib-0.13.2.2/SetupWrapper.hs:86:16:
error:
• Couldn't match expected type ‘IO (PackageIndex.PackageIndex a0)’
with actual type ‘ProgramConfiguration
-> IO PackageIndex.InstalledPackageIndex’
• Probable cause: ‘getInstalledPackages’ is applied to too few arguments
In a stmt of a 'do' block:
index <- getInstalledPackages verbosity usePackageDB conf
In the expression:
do { index <- getInstalledPackages verbosity usePackageDB conf;
let cabalDep
= Dependency
(PackageName "Cabal") (orLaterVersion useCabalVersion);
case PackageIndex.lookupDependency index cabalDep of {
[]
-> die
$ "The package requires Cabal library version "
++
display useCabalVersion ++ " but no suitable version is installed."
pkgs -> return $ bestVersion (map fst pkgs) } }
In an equation for ‘installedCabalVersion’:
installedCabalVersion comp conf
= do { index <- getInstalledPackages verbosity usePackageDB conf;
let cabalDep = ...;
case PackageIndex.lookupDependency index cabalDep of {
[]
-> die
$ "The package requires Cabal library version "
++
display useCabalVersion ++ " but no suitable version is installed."
pkgs -> return $ bestVersion (map fst pkgs) } }
where
bestVersion = maximumBy (comparing preference)
preference version
= (sameVersion, sameMajorVersion, stableVersion, latestVersion)
where
sameVersion = version == cabalVersion
sameMajorVersion
= majorVersion version == majorVersion cabalVersion
....

/var/folders/9b/rh4y2gy92hgdb6ktv4df1jv00000gn/T/cabal-tmp-74552/glib-0.13.2.2/SetupWrapper.hs:86:47:
error:
• Couldn't match expected type ‘Compiler’
with actual type ‘[PackageDB]’
• In the second argument of ‘getInstalledPackages’, namely
‘usePackageDB’
In a stmt of a 'do' block:
index <- getInstalledPackages verbosity usePackageDB conf
In the expression:
do { index <- getInstalledPackages verbosity usePackageDB conf;
let cabalDep
= Dependency
(PackageName "Cabal") (orLaterVersion useCabalVersion);
case PackageIndex.lookupDependency index cabalDep of {
[]
-> die
$ "The package requires Cabal library version "
++
display useCabalVersion ++ " but no suitable version is installed."
pkgs -> return $ bestVersion (map fst pkgs) } }

/var/folders/9b/rh4y2gy92hgdb6ktv4df1jv00000gn/T/cabal-tmp-74552/glib-0.13.2.2/SetupWrapper.hs:120:54:
error:
• Couldn't match type ‘Distribution.Simple.Program.Db.ProgramDb’
with ‘[PackageDB]’
Expected type: PackageDBStack
Actual type: ProgramConfiguration
• In the second argument of ‘cabalLibVersionToUse’, namely ‘conf’
In a stmt of a 'do' block:
cabalLibVersion <- cabalLibVersionToUse comp conf
In the second argument of ‘($)’, namely
‘do { debug verbosity "Setup script is out of date, compiling...";
(comp, _, conf) <- configCompilerEx
(Just GHC) Nothing Nothing defaultProgramConfiguration verbosity;
cabalLibVersion <- cabalLibVersionToUse comp conf;
let cabalPkgid
= PackageIdentifier (PackageName "Cabal") cabalLibVersion;
.... }’
)
bash-3.2$ ghc --version
ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.0.20160204
bash-3.2$

**Comment by RyanGlScott** [comment]
Urgh, this is not going to be a simple fix. The type signature of `getInstalledPackages` (which most of these `SetupWrapper.hs` scripts use) has changed in `Cabal-1.23`.

In `Cabal-1.22`, [its type signature is](http://hackage.haskell.org/package/Cabal-1.22.5.0/docs/Distribution-Simple-GHC.html#v:getInstalledPackages):

```haskell
getInstalledPackages :: Verbosity -> PackageDBStack -> ProgramConfiguration -> IO InstalledPackageIndex
```

But in `Cabal-1.23`, [its type signature is](http://hackage.haskell.org/package/Cabal-1.23.1.0/candidate/docs/Distribution-Simple-GHC.html#v:getInstalledPackages):

```haskell
getInstalledPackages :: Verbosity -> Compiler -> PackageDBStack -> ProgramConfiguration -> IO InstalledPackageIndex
```

Notice the new `Compiler` argument. Working around these kind of changes are never fun, since you're not allowed to use CPP in `SetupWrapper.hs`.

One hack I've seen to get around this is to use a compatibility typeclass that allows you to ignore the `Compiler` argument if necessary. Here's [an example](https://github.com/bscarlet/llvm-general/blob/61fd03639063283e7dc617698265cc883baf0eec/llvm-general/Setup.hs#L52-L65) from `llvm-general`'s `Setup.hs` script:

```haskell
class OldHookable hook where
  preHookOld :: (PackageDescription -> LocalBuildInfo -> UserHooks -> TestFlags -> IO ()) -> hook -> hook

-- this instance is used before Cabal-1.22.0.0, when testHook took four arguments
instance OldHookable (PackageDescription -> LocalBuildInfo -> UserHooks -> TestFlags -> IO ()) where
  preHookOld f hook = \packageDescription localBuildInfo userHooks testFlags -> do
    f packageDescription localBuildInfo userHooks testFlags
    hook packageDescription localBuildInfo userHooks testFlags

-- this instance is used for and after Cabal-1.22.0.0, when testHook took four five arguments
instance OldHookable (Args -> PackageDescription -> LocalBuildInfo -> UserHooks -> TestFlags -> IO ()) where
  preHookOld f hook = \args packageDescription localBuildInfo userHooks testFlags -> do
    f packageDescription localBuildInfo userHooks testFlags
    hook args packageDescription localBuildInfo userHooks testFlags
```

It's ugly, but it works. You could also envision something similar for `getInstalledPackages`:

```haskell
class OldGetInstalledPackages a where
  getInstalledPackagesOld :: a -> Verbosity -> Compiler -> PackageDBStack -> ProgramConfiguration -> IO InstalledPackageIndex

-- Pre Cabal-1.23
instance OldGetInstalledPackages (Verbosity -> PackageDBStack -> ProgramConfiguration -> IO InstalledPackageIndex) where
  getInstalledPackagesOld f v _ db c = f v db c

-- Post-Cabal-1.23
instance OldGetInstalledPackages (Verbosity -> Compiler -> PackageDBStack -> ProgramConfiguration -> IO InstalledPackageIndex) where
  getInstalledPackagesOld = id
```

@hamishmack, does this sound like the right approach? Or would you opt for something different?

**Comment by ethercrow** [comment]
Could you make a hackage release with that fix please?
