### ISSUE TITLE
gtk3 with 8.0.1

### ISSUE THREAD

**Issue by andrewufrank** [gtk2hs/gtk2hs#174]
compiling gtk3 with 8.0.1 gives the error
```
StockItems.hsc:814:5: warning: ‘GtkStock’ is deprecated [-Wdeprecated-declarations]
gtk2hsC2hs: Errors during expansion of binding hooks:

./Graphics/UI/Gtk/Layout/Stack.chs:292: (column 11) [ERROR] 
  >>> Unknown identifier!
  Cannot find a definition for `stack_set_hhomogeneous' in the header file.
```

what can be done to fix this? 
using a fresh cabal 1.24

**Comment by hamishmack** [comment]
It looks like when we added support for [GtkStack](https://developer.gnome.org/gtk3/stable/GtkStack.html) we left some of the `#if`s needed for older versions of Gtk.

For instance [gtk-stack-set-hhomogeneous](https://developer.gnome.org/gtk3/stable/GtkStack.html#gtk-stack-set-hhomogeneous) is only supported on Gtk+ 3.16.

Adding new Gtk+ features to Gtk2Hs is time consuming and hard to get right.  That is the big advantage of [haskell-gi](https://github.com/haskell-gi/haskell-gi).

**Comment by andrewufrank** [comment]
this fix would perhaps been useful. i may try 8.0.1 again in a week or so.

-- 
Prof. Dr. sc.techn. Dr. h.c. Andrew U. Frank
                 +43 1 58801 12710 direct
Geoinformation, TU Wien          +43 1 58801 12700 office
Gusshausstr. 27-29               +43 1 55801 12799 fax
1040 Wien Austria                +43 676 419 25 72 mobil
