### ISSUE TITLE
Gtk+-3.0 support?

### ISSUE THREAD

**Issue by erikd** [gtk2hs/gtk2hs#188]
Is Gtk+-3.0 support planned? Gtk+-2.0 is not longer available in Debian Testing and Gtk+2.0 is rather a pain on high resolution displays (my laptop is 3840x2160).

**Comment by jplatte** [comment]
What exactly are you talking about? The libgtk2.0-0 package is [still there](https://packages.debian.org/stretch/libgtk2.0-0). And I heavily doubt Debian, or any other distro, will drop gtk2 in the next years; there's many popular programs that will still take quite a while to be ported fully to gtk3 (e.g. GIMP, Chromium and all the Electron-based stuff, Pidgin, LibreOffice).

That said, gtk2hs does support gtk3, and has done so for quite a while. If you're looking for support of all the widgets in more recent gtk3 versions though, you should have a look at [haskell-gi][], or more specifically [gi-gtk][] and [gi-gtk-hs][].

[haskell-gi]: https://github.com/haskell-gi/
[gi-gtk]: https://hackage.haskell.org/package/gi-gtk
[gi-gtk-hs]: https://hackage.haskell.org/package/gi-gtk-hs

**Comment by erikd** [comment]
Wow, there used to be a `+` character in the package name. Really glad they dropped that.

Since I'm doing something that requires good text handling, something gtk3 based would probably be better. I had a look at gi-gtk, but it failed to cabal install. At least gi-gtk-hs installed.

**Comment by jplatte** [comment]
gi-gtk-hs depends on gi-gtk, so I'm not sure how you'd be able to install the former without installing the latter. But I guess this issue can be closed now either way, right? If you have problems with installing (or using) haskell-gi generated libraries, it has its own issues (and gitter.im chat).
