### ISSUE TITLE
Mismatched cabal versions somehow causing build failures

### ISSUE THREAD

**Issue by IvanMalison** [gtk2hs/gtk2hs#195]
Whenever I try to build cairo, or anything depending on it, I get an error about mismatched cabal versions that I can't make much sense of.

Here is a sample error log: https://gist.github.com/079f477962336f4feeee7baac2f1ead3

I'm running arch linux with the cabal package installed (this shouldn't be relevant though right?)

I ran the intructions in the README 

```
git clone --recursive https://github.com/leksah/leksah.git
cd leksah
stack install alex happy
stack install haskell-gi
stack install gtk2hs-buildtools
stack install
```

for installing leksah and got the same thing.

I suspect that I have set something up incorrectly, but its hard to tell what that might be. Any help would be appreciated.

**Comment by hamishmack** [comment]
I have just updated the instructions based on what worked for @kgish (see https://github.com/leksah/leksah/issues/413).  New instructions are at https://github.com/leksah/leksah/blob/master/Readme.md#build-with-stack.  Please let us know if that fixes it for you.

**Comment by kgish** [comment]
Thanks!

**Comment by hamishmack** [comment]
I think this is fixed
