### ISSUE TITLE
Build Error on Stackage 8.11

### ISSUE THREAD

**Issue by devonhollowood** [gtk2hs/gtk2hs#201]
Hello,

I'm getting the following build error when building the `gtk` package (on MacOS, if that matters):

    /private/var/folders/l0/nbsgfskn5cd4q36p4136h3p40000gn/T/stack57143/gtk-0.14.6/Graphics/UI/Gtk/Embedding/Plug.chs:120:6: error:
        • Couldn't match expected type ‘Ptr ()’
                      with actual type ‘Maybe DrawWindow’
        • In the first argument of ‘gtk_plug_new’, namely
            ‘(fromNativeWindowId (fromMaybe nativeWindowIdNone socketId))’
          In the second argument of ‘($)’, namely
            ‘gtk_plug_new
               (fromNativeWindowId (fromMaybe nativeWindowIdNone socketId))’
          In the second argument of ‘($)’, namely
            ‘liftM (castPtr :: Ptr Widget -> Ptr Plug)
             $ gtk_plug_new
                 (fromNativeWindowId (fromMaybe nativeWindowIdNone socketId))’

    /private/var/folders/l0/nbsgfskn5cd4q36p4136h3p40000gn/T/stack57143/gtk-0.14.6/Graphics/UI/Gtk/Embedding/Plug.chs:137:6: error:
        • Couldn't match expected type ‘Ptr ()’
                      with actual type ‘Maybe DrawWindow’
        • In the second argument of ‘\ (Display arg1) arg2
                                       -> withForeignPtr arg1
                                          $ \ argPtr1 -> gtk_plug_new_for_display argPtr1 arg2’, namely
            ‘(fromNativeWindowId (fromMaybe nativeWindowIdNone socketId))’
          In the second argument of ‘($)’, namely
            ‘(\ (Display arg1) arg2
                -> withForeignPtr arg1
                   $ \ argPtr1 -> gtk_plug_new_for_display argPtr1 arg2)
               display
               (fromNativeWindowId (fromMaybe nativeWindowIdNone socketId))’
          In the second argument of ‘($)’, namely
            ‘liftM (castPtr :: Ptr Widget -> Ptr Plug)
             $ (\ (Display arg1) arg2
                  -> withForeignPtr arg1
                     $ \ argPtr1 -> gtk_plug_new_for_display argPtr1 arg2)
                 display
                 (fromNativeWindowId (fromMaybe nativeWindowIdNone socketId))’

    /private/var/folders/l0/nbsgfskn5cd4q36p4136h3p40000gn/T/stack57143/gtk-0.14.6/Graphics/UI/Gtk/Embedding/Plug.chs:151:3: error:
        • Couldn't match type ‘Ptr ()’ with ‘Maybe DrawWindow’
          Expected type: IO (Maybe DrawWindow)
            Actual type: IO (Ptr ())
        • In the second argument of ‘($)’, namely
            ‘(\ (Plug arg1)
                -> withForeignPtr arg1 $ \ argPtr1 -> gtk_plug_get_id argPtr1)
               (toPlug self)’
          In the expression:
            liftM toNativeWindowId
            $ (\ (Plug arg1)
                 -> withForeignPtr arg1 $ \ argPtr1 -> gtk_plug_get_id argPtr1)
                (toPlug self)
          In an equation for ‘plugGetId’:
              plugGetId self
                = liftM toNativeWindowId
                  $ (\ (Plug arg1)
                       -> withForeignPtr arg1 $ \ argPtr1 -> gtk_plug_get_id argPtr1)
                      (toPlug self)

Any idea what could be causing this?

**Comment by hamishmack** [comment]
The `gtk` package had a cabal flag `have-quartz-gtk` that needs to be on if you are using Gtk+ compiled for Quartz and needs to be off if you are using an X11 build of Gtk+.  Unfortunately in Gtk+ 2 there is no good way to detect this so the flag must be set manually.  Gtk+ 3 does not have this problem and the Haskell packages `gtk3` and `gi-gtk` will both build correctly without the need to specify the Gtk+ backend used.

**Comment by devonhollowood** [comment]
Thank you.
