### ISSUE TITLE
Build failure of gtk-0.14.6 with ghc 8.2.1 (base 4.10)

### ISSUE THREAD

**Issue by xaverdh** [gtk2hs/gtk2hs#216]
I get the following error, which did not occur with ghc 8.0 (base 4.9.1) :
`Graphics/UI/Gtk/Embedding/Types.chs:48:28: error:`
`Module ‘Foreign.ForeignPtr’ does not export ‘unsafeForeignPtrToPtr’`
`import Foreign.ForeignPtr (unsafeForeignPtrToPtr)`

Perhaps related to the issue with cpphs (version 1.20.8 here)?
Potentially relevant: [ghc-ticket](https://ghc.haskell.org/trac/ghc/ticket/13553)

By the way im on arch linux, so maybe this is slightly different from the problem in the ghc-ticket.

**Comment by xaverdh** [comment]
Edit: The problem is only with the current package on hackage, building directly from master suceeds.

**Comment by hamishmack** [comment]
I have uploaded gtk-0.14.7 to hackage.
