### ISSUE TITLE
on ghc 8.2.2. gtk uses old versions of process and Cabal

### ISSUE THREAD

**Issue by GeorgeCo** [gtk2hs/gtk2hs#222]
ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.2.1.20171108
has
 Cabal-2.0.1.0
 process-1.6.1.0
but gtk uses much older versions:
cabal install -j5 gtk
...
Installed process-1.4.3.0
Configuring Cabal-1.24.2.0...
...
Not major but it would be nice to use the same versions as 8.2.2

**Comment by hamishmack** [comment]
I think this should have been fixed by gio-0.13.4.0.  Please reopen this issue if it was not.

**Comment by GeorgeCo** [comment]
Doesn't seem to be fixed, not sure how to reopen
cabal install -j5 gio
...
Installed process-1.4.3.0
Configuring Cabal-1.24.2.0...
...
Configuring gio-0.13.4.0...
...
 ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.2.2
bash-3.2$ cabal --version
cabal-install version 2.0.0.0
compiled using version 2.0.1.0 of the Cabal library

**Comment by GeorgeCo** [comment]
according to https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github
I can't reopen it as I didn't close it
as suggested there. Can someone reopen it? Or do you want me to   open a new issue and reference this one by referencing #222

**Comment by GeorgeCo** [comment]
problem seems to be fixed in  gio-0.13.4.1
