### ISSUE TITLE
Add github tags for newer hackage releases

### ISSUE THREAD

**Issue by chessai** [gtk2hs/gtk2hs#224]
Recently I was debugging an issue in an application related to a build failure of a version of gtk2hs that I was using. GitHub tags for the Hackage releases are useful in such situations, however it doesn't seem that gtk2hs Hackage releases have been tagged on GitHub for quite some time (since 0.12.4, 5 years ago). I believe it would be generally useful to have these tags.

**Comment by hamishmack** [comment]
I'll try to remember to add these from now on.  Someone really needs to make a tool to automate this somehow.  For bonus points it would be nice if it could also commit changes made to the .cabal file on Hackage to a github branch based on the tagged commit.

**Comment by chessai** [comment]
Thank you. And yes, I was thinking the same thing. I wonder if it's possible with Hydra (https://github.com/NixOS/hydra)?
