### ISSUE TITLE
Can't install gtk2hs-buildtools on a fresh Ubuntu 16.04 install

### ISSUE THREAD

**Issue by jsmaniac** [gtk2hs/gtk2hs#225]
On a fresh install of xUbuntu 16.04 with the latest updates (GHC 7.10), I cannot install `gtk2hs-buildtools`:

```
sudo apt -y install ghc cabal-install alex happy
cabal update
cabal install gtk2hs-buildtools
```

Produces the error:

```
src/Gtk2HsSetup.hs:371:45: Not in scope: ‘versionBranch’
Failed to install gtk2hs-buildtools-0.13.3.0
cabal: Error: some packages failed to install:
gtk2hs-buildtools-0.13.3.0 failed during the building phase. The exception
was:
ExitFailure 1
```

This in turn makes it difficult to install `leksah` which depends (or rather used to depend) on gtk2hs.

**Comment by hvr** [comment]
@hamishmack I know what the problem here is; but I currently can't fix this in an exact surgical way via revisions yet (inconsistent CPP conditionals in `src/Gtk2HsSetup.hs`). Would it be possible to make a `0.13.3.1` point-release to fix the CPP?

**Comment by hamishmack** [comment]
I have uploaded 0.13.3.1.  It should resolve this issue.
