### ISSUE TITLE
gio is incompatible with Cabal-2.0

### ISSUE THREAD

**Issue by debug-ito** [gtk2hs/gtk2hs#226]
Maybe related to #222 and f066503df2c6d8d57e06630615d2097741d09d39.

setup-depends of gio still rejects Cabal-2.0.

This makes gio (and gtk) to be removed from stackage (see https://github.com/fpco/stackage/issues/2683 ), which makes some of my packages to be also removed from stackage (see https://github.com/fpco/stackage/issues/3048 )

**Comment by hamishmack** [comment]
I have uploaded gio-0.13.4.0 to hackage with updated upper bound

**Comment by debug-ito** [comment]
Thanks!

**Comment by debug-ito** [comment]
@hamishmack  I saw the gio.cabal of gio-0.13.4.0 , but it does not support Cabal-2.0.

Sorry I didn't notice a month ago.

**Comment by hamishmack** [comment]
Ooops.  Not sure how I got that wrong. I've uploaded 0.13.4.1 to hackage (fairly sure I got it right this time).

**Comment by debug-ito** [comment]
Thanks! I confirmed the gio.cabal and LGTM
