### ISSUE TITLE
How do I change background color of a button?

### ISSUE THREAD

**Issue by unclechu** [gtk2hs/gtk2hs#234]
How can I do it? Or how could I set look of a button like its pressed? I haven't found any related methods in docs, did I missed something?

**Comment by unclechu** [comment]
I just found a solution but it doesn't work (I haven't seen constructors for `Color` type but realized it exists), so I'm trying to do:
```haskell
widgetOverrideBackgroundColor btn StateNormal $ Just $ Color maxBound 0 0
```
But it have no effect on button appearance.

**Comment by unclechu** [comment]
I even tried this:
```haskell
  forM_ (enumFrom StateNormal) $
    \stateType → widgetOverrideBackgroundColor btn stateType $ Just $ Color maxBound 0 0
```
But with no success.

**Comment by unclechu** [comment]
I realized that overriding text color have some effect but it isn't what I expected to see.
```haskell
widgetOverrideColor btn StateNormal $ Just $ Color maxBound 0 0
```
It goes black from white, I tried also `255`, `1` instead of `maxBound` but got no difference.
![screenshot from 2018-01-28 20-33-59](https://user-images.githubusercontent.com/799353/35483975-9814a85c-046a-11e8-8ad6-df8b021a8c30.png)

**Comment by unclechu** [comment]
I realized I could do it using `Graphics.UI.Gtk.Selectors.ColorButton` but `colorButtonTitle` never appears on a button, so I could use only without any labels. I still need a solution.

**Comment by rsilvis** [comment]
Here's the relevant section of the documentation for how to style widgets using CSS, which is the recommended method:

https://developer.gnome.org/gtk3/stable/chap-css-properties.html

https://developer.gnome.org/gtk3/stable/chap-css-overview.html

**Comment by unclechu** [comment]
@rsilvis Thanks for the hint, now I realized how I do this.

If anyone interested how I did it could look at this commit:
https://github.com/metachronica/audio-midihaskey/commit/ff1310fb89f70d859430253bc9a7995b7875955c
![screenshot from 2018-02-27 03-47-08](https://user-images.githubusercontent.com/799353/36700394-5814f41e-1b71-11e8-8c4a-6f2f68dd7e78.png)
