### ISSUE TITLE
How do I create dropdown menu?

### ISSUE THREAD

**Issue by unclechu** [gtk2hs/gtk2hs#235]
I'm creating menu by this code:
```haskell
menu ← menuNew
set menu [menuTitle := "Select a MIDI channel"]

menuItem ← menuItemNew
set menuItem [menuItemLabel := "some item"]
on menuItem menuItemActivated $ putStrLn "some item is activated"

menuShellAppend menu menuItem
```
And then by clicking on a button I'm trying to show it:
```haskell
channelBtn ← buttonNew
set channelBtn [buttonLabel := "Channel: " ⧺ show (succ $ fromChannel currentChannel)]
on channelBtn buttonActivated $ menuPopup menu Nothing
```
But when menu is opened I don't see the item I added, only empty menu with height of few pixels:
![screenshot from 2018-01-29 22-59-02](https://user-images.githubusercontent.com/799353/35526043-1dff5628-0548-11e8-80d0-6ceb52487226.png)
Am I doing something wrong?

**Comment by unclechu** [comment]
Can someone tell is it a bug or did I missed something?

**Comment by PaulJohnson** [comment]
Try adding
  `widgetShowAll menu`

**Comment by unclechu** [comment]
@PaulJohnson Thanks! That works! I added this line after `menuShellAppend` line (after I set everything up)/
