### ISSUE TITLE
gtk2hs-buildtools has missing version constraint for hashtables

### ISSUE THREAD

**Issue by cohomology** [gtk2hs/gtk2hs#243]
In gtk2hs-buildtools.cabal there are no version constraints for hashtables. This is a petty, as hashtables 1.2.3.0 [dropped](https://github.com/gregorycollins/hashtables/issues/48) support for < GHC 7.10. 

What to do about it? 

I could make a pull request to:
   1.  Drop support for GHC 7.8 as well and include a version constraint on hashtables 1.2.3.0. Also the 
        .travis scripts must be adapted for that.
   2.  Add a version constaint on hashtables < 1.2.3.0

**Comment by hamishmack** [comment]
I went with option 1.  If anyone is still using ghc 7.8 I think they might be able to constrain hashtables in their cabal config file.
