### ISSUE TITLE
gtk-0.14.9 should have bumped the second version component

### ISSUE THREAD

**Issue by maoe** [gtk2hs/gtk2hs#247]
#239 was a breaking change on an existing function so the version number should be 0.15.0 if it follows the PVP. Does this project comply with PVP?

**Comment by hamishmack** [comment]
I was not sure how to fix this and forgot about it until yesterday.  Thanks heaps to @hvr, who reminded me about this issue and explained a solution.  We have uploaded a 0.15.0 version and deprecated the 0.14.9 and 0.14.10 versions (for both gtk and gtk3).

**Comment by maoe** [comment]
Thanks for fixing the issue!
