### ISSUE TITLE
Upload new version of gtk2hs-buildtools to Hackage

### ISSUE THREAD

**Issue by osa1** [gtk2hs/gtk2hs#263]
The one on Hackage doesn't build with GHC 8.6.3. The one on the git repo works, but I don't know how to override build tools in .cabal/.cabal.project so currently it's hard to distribute packages that need gtk2hs-buildtools + GHC 8.6.3. It'd be helpful to upload current version to Hackage.

**Comment by hamishmack** [comment]
Done.

**Comment by osa1** [comment]
Thanks!
