### ISSUE TITLE
Relax bound on Cabal in cairo.cabal

### ISSUE THREAD

**Issue by garetxe** [gtk2hs/gtk2hs#294]
Hi,

Would it be possible to relax the `Cabal >= 1.24 && < 3.1` in the `custom-setup` stanza of `cairo.cabal`? It seems to build fine with `Cabal-3.2` other than this.

Thanks a lot in advance!

**Comment by hamishmack** [comment]
Done.

**Comment by garetxe** [comment]
Thanks!
