### ISSUE TITLE
cairo can not build with ghc-9.4.3

### ISSUE THREAD

**Issue by wkoiking** [gtk2hs/gtk2hs#323]
I could not build cairo with Stackage nightly-2022-11-23 (ghc-9.4.3) with below error:

~~~
\src\Gtk2HsSetup.hs:(297,20)-(304,1): Missing field in record construction ppOrdering
~~~

The same issue apply to glib and pango package.

I could avoid the error by making below change to gtk2hs-buildtools:

![image](https://user-images.githubusercontent.com/3189740/203522065-a04a2e6d-f11b-4490-990e-1cce175eb23f.png)

**Comment by sternenseemann** [comment]
Additionally the upper constraints on `text` (in glib, pango, cairo, …) need to be relaxed to allow `2.0.*`.

**Comment by cartazio** [comment]
i've hit this issue myself, how can we help get a release out?

**Comment by jamesdbrock** [comment]
I would also like a new release please.

**Comment by ocharles** [comment]
Can I join the crowd and ask for a release? This is one of the few packages stopping us from getting to GHC 9.4, we're so close! :pray:

**Comment by ocharles** [comment]
@hamishmack able to lend a hand here?

**Comment by jamesdbrock** [comment]
I nominate @wkoiking @sternenseemann @cartazio @ocharles to be added to the Hackage maintainers list for this whole family of packages.

**Comment by ocharles** [comment]
I would accept that, though I don't really know the internals. But I'm happy to do the odd bump and release

**Comment by jamesdbrock** [comment]
It looks like #329 fixes this? There is a new version on Hackage, thanks @hamishmack . https://hackage.haskell.org/package/gtk2hs-buildtools
