### ISSUE TITLE
text >= 2.0 breaks the build

### ISSUE THREAD

**Issue by hellwolf** [gtk2hs/gtk2hs#327]
Related to https://github.com/NixOS/nixpkgs/pull/227690.

Removing the upper bound version checks suggest that the build should still work. Please consider to bump the version for "text" package.

**Comment by andreasabel** [comment]
The current bound is `text < 2.1` which is good enough for GHC 9.6....

**Comment by hamishmack** [comment]
I think this is fixed.  If not please add new issue with steps to reproduce the build failure.
