### ISSUE TITLE
Windows threading/mutex error

### ISSUE THREAD

**Issue by cchantep** [gtk2hs/gtk2hs#33]
As error with GTK3/win mentionned [there](https://sourceforge.net/p/gtk2hs/mailman/message/32021937/), we get the same error with GTK2:

```
message:Glib:ERROR:gthread-win32.c:640:g_thread_xp_AcquireSRWLockExclusive: assertion failed:(!lock->writer_locked)
```

It's reproduced on Win7 and WinXP, using glib/gtk libraries provided by MSYS2 (by pacman) on Win7, using built from sources glib/gtk on WinXP, with same error: as soon as window is altered (moved or resized), application is locked.

On Win7, same app (same .exe file) work by replacing .dll by those found [there](https://github.com/applicius/dhek/tree/master/util/win-dist/dlls) (extracted from GIMP). On WinXP even this 'workaround' can't make it work.

Considering other GTK/GLib apps (GIMP, Inkscape, Pidgin, ...) are working properly on same OSes (same VM), I don't think cause is GTK itself, but way it's used.

As Win7 workaround, using previous/older GTK/Glib .dll, I can guess some GTK or Glib changes for Win (gthread-win32) haven't been considered, so that [hsgthread.c](https://github.com/gtk2hs/gtk2hs/blob/master/gtk/Graphics/UI/Gtk/General/hsgthread.c) is no longer compliant.

**Comment by emmanueltouzery** [comment]
I think this can be closed now that https://github.com/gtk2hs/gtk2hs/pull/91 was merged.
