### ISSUE TITLE
Tray icons disappear very quickly if "-threaded" ghc-option is used

### ISSUE THREAD

**Issue by namore** [gtk2hs/gtk2hs#60]
If the ghc option "-threaded" is used, tray icons will show up and then disappear after half a second.

How to reproduce:

1. Save the following sample (*test.hs*): 

```haskell
import Graphics.UI.Gtk
import Graphics.UI.Gtk.Display.StatusIcon

main :: IO ()
main = do
  initGUI
  tray <- statusIconNewFromFile "test.jpg"
  mainGUI
```

2. Place any image in the same directory as *test.hs* and name it *test.jpg*

3. Compile without threaded and see if the image shows up properly in tray:

```shell
$ ghc test.hs
$ ./test # tray image should show up properly now
```

4. Compile *with* threaded option, see how the tray icon disappears after a split second:

```shell
$ ghc -threaded test.hs
$ ./test # tray icon wont stay this time
```

**Comment by khumba** [comment]
This seems to be because the Haskell reference to the tray icon is getting GCed and is destroying the icon.  If you hold on to the icon, it doesn't disappear:

```haskell
import Data.IORef
import Graphics.UI.Gtk
import Graphics.UI.Gtk.Display.StatusIcon

main :: IO ()
main = do
  initGUI
  ref <- newIORef =<< statusIconNewFromStock stockSave
  mainGUI
  readIORef ref    -- Necessary.
  return ()
```

**Comment by namore** [comment]
Thanks, khumba! This resolves the issue.
