### ISSUE TITLE
glib doesn't compile with 7.10.RC1

### ISSUE THREAD

**Issue by GeorgeCo** [gtk2hs/gtk2hs#87]
glib doesn't compile with 7.10.RC1

cabal install glib
Resolving dependencies...
Configuring glib-0.13.0.7...
Failed to install glib-0.13.0.7
Build log ( /Users/gcolpitts/.cabal/logs/glib-0.13.0.7.log ):
cabal: Error: some packages failed to install:
glib-0.13.0.7 failed during the configure step. The exception was:
user error ('/usr/local/bin/ghc' exited with an error:

/var/folders/9b/rh4y2gy92hgdb6ktv4df1jv00000gn/T/glib-0.13.0.7-4073/glib-0.13.0.7/SetupWrapper.hs:91:17:
Ambiguous occurrence ‘die’
It could refer to either ‘Distribution.Simple.Utils.die’,
imported from ‘Distribution.Simple.Utils’ at
/var/folders/9b/rh4y2gy92hgdb6ktv4df1jv00000gn/T/glib-0.13.0.7-4073/glib-0.13.0.7/SetupWrapper.hs:8:1-32
or ‘System.Exit.die’,
imported from ‘System.Exit’ at
/var/folders/9b/rh4y2gy92hgdb6ktv4df1jv00000gn/T/glib-0.13.0.7-4073/glib-0.13.0.7/SetupWrapper.hs:21:1-18
)

**Comment by ghorn** [comment]
Still an issue with 7.10 RC2. It seems that base-4.8 added `System.Exit.die`. Changing to
`import System.Exit hiding ( die )` solves the problem.

This applies to every gtk2hs project with this SetupWrapper.hs, not just glib

**Comment by ghorn** [comment]
This was fixed with e150f4448d6fb7da1c66561fd7aa3b207eff598c, the issue can be closed

**Comment by GeorgeCo** [comment]
Thanks Greg, when will that fix be available via cabal install?

**Comment by ghorn** [comment]
Sorry but I have no idea. I'm not a gtk2hs developer, I just looked through the recent commits. I imagine that as long as the build is failing on 7.10 (https://travis-ci.org/gtk2hs/gtk2hs) there will be no upload.

**Comment by GeorgeCo** [comment]
Thanks Greg

**Comment by hamishmack** [comment]
This should be fixed now in hackage.
