### ISSUE TITLE
Cabal 1.22 issues

### ISSUE THREAD

**Issue by pacak** [gtk2hs/gtk2hs#88]
compiling of gtk with ghc 7.10.1rc fails with a lot of duplicate modules errors. It's possible to fix it by modifying cabal file to exclude all the modules except for the topmost, but that doesn't look like a proper solution.

I'm pretty sure it's related to this change somehow:
http://osdir.com/ml/general/2014-08/msg52041.html

**Comment by RyanGlScott** [comment]
Here's an example of this error when building `gio` with GHC 7.10.1-rc2:

```
In-place registering gio-0.13.0.5...
setup: '/home/rscott/opt/haskell/ghc/bin/ghc-pkg' exited with an error:
gio-0.13.0.5: Warning: haddock-interfaces:
/home/rscott/Documents/Hacking/Haskell/gtk2hs/gio/dist/doc/html/gio/gio.haddock
doesn't exist or isn't a file
gio-0.13.0.5: Warning: haddock-html:
/home/rscott/Documents/Hacking/Haskell/gtk2hs/gio/dist/doc/html/gio doesn't
exist or isn't a directory
gio-0.13.0.5: package has duplicate modules: System.GIO.Async.Cancellable
System.GIO.File.AppInfo System.GIO.File.ContentType System.GIO.File.File
System.GIO.File.FileAttribute System.GIO.File.FileEnumerator
System.GIO.File.FileInfo System.GIO.File.FileMonitor System.GIO.File.IOError
System.GIO.File.MountOperation System.GIO.Icons.Emblem
System.GIO.Icons.EmblemedIcon System.GIO.Icons.FileIcon System.GIO.Icons.Icon
System.GIO.Icons.ThemedIcon System.GIO.Volumes.Drive System.GIO.Volumes.Mount
System.GIO.Volumes.Volume System.GIO.Volumes.VolumeMonitor (use --force to
override)
Failed to install gio-0.13.0.5
cabal: Error: some packages failed to install:
gio-0.13.0.5 failed during the building phase. The exception was:
ExitFailure 1
```

Sure enough, running `cabal install --ghc-pkg-option=--force` will bypass the issue.

**Comment by bergey** [comment]
Some links, in case others are looking at this.

This bug prompted the patches below: https://ghc.haskell.org/trac/ghc/ticket/8407

These patches look relevant; the second is the one @pacak linked:
https://phabricator.haskell.org/rGHC7f5c10864e7c26b90c7ff4ed09d00c8a09aa4349
https://phabricator.haskell.org/rGHC4b648be19c75e6c6a8e6f9f93fa12c7a4176f0ae
https://github.com/haskell/cabal/commit/62450f9a81bb7efccf1325a6addb15f693dcf755

Diagrams reexports lots of modules, without this error: https://github.com/diagrams/diagrams-lib/blob/master/src/Diagrams.hs

I'm wondering the custom build for `gio` interacts badly with the `ghc-pkg` changes above.  I'm still unsure whether this is a GHC bug or a deliberate change of behavior.
